[phases.setup]
nixPkgs = ["nodejs_22"]
cmds = ["export NODE_VERSION=22.12.0"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build:prod"]

[start]
cmd = "node proxy-server.js"

